#!/bin/bash

if [ ! -f /home/pi/.vnc/passwd ]; then

    echo "/home/pi/.vnc/passwd not found, creating new random password for vnc"
    RANDOM_PASSWORD=$(dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 -w 0 | rev | cut -b 2- | rev)
    sudo -u pi /home/pi/scripts/setX11vncPass echo RANDOM_PASSWORD
    exit 1

fi

while true
do
    if [ $(curl -sL -w "%{http_code}\\n" "http://localhost/FullPageDashboard" -o /dev/null) == "200" ] || grep -q disabled "/boot/check_for_httpd" ; then
      (sleep 15 ; /home/pi/scripts/fullscreen) &
      xdotool mousemove 9000 9000
      %BROWSER_START_SCRIPT%
    fi
    sleep 1
done
